### ISSUE TITLE
[Bug] Token shaking movement affects auras.

### ISSUE THREAD

**Issue by pedrogrullada** [ChasarooniZ/pf2e-rpg-numbers#10]
**Describe the bug**
When a token shakes, its aura shakes with it, causing unexpected behaviour such as neighbouring tokens being briefly affected by an aura in quick succession. On top of looking weird visually, I suspect it could cause serious lag on certain clients.

**To Reproduce**
1. Enable Token Shaking
2. Place a token whose actor possesses an aura, preferably one that grants some type of effect or condition, as to visualise the bug better (I used a Cinder Rat).
3. Place a different token on a neighbouring square to the aura, just outside of it.
4. Damage any of the involved tokens, and as it shakes it will enter and exit the aura in quick succession.

**Expected behavior**
Movement and shaking being purely cosmetic, hopefully not interacting with auras nor any system automation.

**Screenshots**

https://github.com/ChasarooniZ/pf2e-rpg-numbers/assets/103401186/f4bfbb48-b909-4cf3-b275-1e1eab7cff7a

On Foundry V11, PF2E 5.11.5, Google Chrome.

This is a very neat module, I enjoy instantaneous, understated animations!

**Comment by ChasarooniZ** [comment]
Ah darn, I was hoping this wouldn't be the case, but okay. I implemented what i'd call a very rudimentary way to add shaking using Sequencer, but I'm going to have to go back to the drawing board on it. For the mean time in the next update I'll  add a warning clearly stating it can cause issues with auras.

But the module I took the idea from (Target Reacts) uses the Token Magic FX module which I was hoping to get by without having to include it but maybe it's worth looking into seeing how that module might help this one.

Thank you also for your kind feedback, this module has always been on my I wish it existed, so I'm glad someone else appreciates the little animations  😊

Sorry it took so long for me to get on this, I was away on holiday so wasn't checking many issues etc.
