### ISSUE TITLE
Don't show damage in PF2e

### ISSUE THREAD

**Issue by Javierusan** [ChasarooniZ/pf2e-rpg-numbers#11]
Hello, I have installed this module but it does not work. Neither the gamemaster nor the players see the damage. It can only be seen by the gamemaster when the "Only GM" option is activated. If it is not activated, nothing is seen (GM or PCs).
any solution? thx

**Comment by ChasarooniZ** [comment]
Has been addressed by DrentalBot  on discord. Will be merging and pushing an update that deals with issue. Issue crops up due to me adding an accidental require dependency for Pf2e Perception module.
