### ISSUE TITLE
[Bug] From Software Noun-Verbed always playing after combat

### ISSUE THREAD

**Issue by serbandr** [ChasarooniZ/pf2e-rpg-numbers#116]
**Describe the bug**
The (by default) "Enemy Felled" screen always plays when ending combat, no matter whether the option is ticked on or off. This has been the case ever since the last patch - when before it would never play despite it being on or off.

**To Reproduce**
1. Begin a combat.
2. End a combat.

**Expected behavior**
The "Show on end of encounter" button should dictate whether it plays.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - FVTT: v12.331
 - RPG numbers: 12.6.8

**Additional context**

**Comment by ChasarooniZ** [comment]
Should be fixed in `12.6.9`

**Comment by serbandr** [comment]
I think you might have accidentally reversed it? Now it plays when it should be turned off and vice versa for me

**Comment by ChasarooniZ** [comment]
HI. yeah, i mixed up the variable state, should be fixed in `.10`
