### ISSUE TITLE
[Bug] Critical Animation not showing up

### ISSUE THREAD

**Issue by CrimWolfe** [ChasarooniZ/pf2e-rpg-numbers#117]
**Describe the bug**
Two weeks ago I was using the module and it would show the Persona critical animation without a problem. As I played a game yesterday, the sound would come but no animation. Today I have been trying and changing settings and no use. I even went and only had the module on by itself. When tried with the Fire Emblem critical animation, it varies. I've seen it come very slowly but no red background, just the token floating in the air. I tried increasing the time and still would not appear with the Persona one and the Fire Emblem the token would come out but stay on the right side of the screen.

**To Reproduce**
1. Just using the critical animation

**Expected behavior**
Expected to see the critical animation screen.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari]: Tried on both Chrome and Edge
 - Version [e.g. 22]: 131.0.6778.86 and 131.0.2903.63 respectively

**Comment by ChasarooniZ** [comment]
It's an issue with newest Sequencer version, either revert versions or wait for the fix being pushed in a week or so
