### ISSUE TITLE
After most recent update, Persona style critical animations stopped playing

### ISSUE THREAD

**Issue by Dominemesis** [ChasarooniZ/pf2e-rpg-numbers#118]
Title:  I updated to the most recent update, and the critical hit animations stopped working.  

The following console errors showed. 
![PF2rpgnumbers console errors](https://github.com/user-attachments/assets/bb637137-1928-41c5-828d-e632c2b2bca3)

**Comment by ChasarooniZ** [comment]
Sequencer `3.4.5` is the culprit, revert to an earlier version or wait for sequencer update

**Comment by Dominemesis** [comment]
> Sequencer `3.4.5` is the culprit, revert to an earlier version or wait for sequencer update

Ok, thank you!
