### ISSUE TITLE
[Bug] On Roll Damage Numbers isn't properly coloring fields

### ISSUE THREAD

**Issue by TomChristoffer** [ChasarooniZ/pf2e-rpg-numbers#18]
Suggestion: Different colors depending on damage type, based on the colors of damage types in the system already present in the chat cards.

**Comment by ChasarooniZ** [comment]
This should already be a feature?

**Comment by ChasarooniZ** [comment]
If you could troubleshoot and tell me what situation has no damage colors I'd be curious to see

**Comment by ChasarooniZ** [comment]
Updated colors to match system in latest update

**Comment by TomChristoffer** [comment]
> If you could troubleshoot and tell me what situation has no damage colors I'd be curious to see

I only get white damage numbers. Right now I'm testing with Ignition (fire damage) and it's generating white numbers. Although some other things are currently strange aswell. The 'On Roll' mode isn't working at all, only 'on apply', and tokens are shaking even through the 'tokens shake on damage apply' is turned off. I'm not sure what's going on

**Comment by ChasarooniZ** [comment]
Ah okay I'll look into it at some point later, probably broke it with the newest on Apply addon

**Comment by ChasarooniZ** [comment]
This should be fixed as of most recent release
