### ISSUE TITLE
[Feature Request] Setting to turn off critical hit animations for certain actor types

### ISSUE THREAD

**Issue by pedrogrullada** [ChasarooniZ/pf2e-rpg-numbers#19]
I showed my players the persona 5 cut-ins and they are delighted, thank you. I have a feature request specifically related to this feature.

**Is your feature request related to a problem? Please describe.**
Depending on their portrait, NPCs will be misaligned in their cut ins, making it look strange (like only showing their torso, for example)

**Describe the solution you'd like**
A setting to turn off the critical hit animation for NPCs by default, allowing it to be overridden by manually enabling it on a specific NPC (perhaps via the existing tab added to the Token Settings menu.)

**Describe alternatives you've considered**
Alternatively, or additionally, perhaps a way to offset the X and Y alignments of the cut-ins can let us align the picture correctly. Perhaps a preview button that plays the animation could be added to the Token menu, which would make testing that the picture is aligned correctly easier. Of course, this is getting a bit out of scope of this feature request.

**Additional context**
Here is a screenshot of the issue I'm looking to avoid
![image](https://github.com/ChasarooniZ/pf2e-rpg-numbers/assets/103401186/e67e7676-eb53-430b-8ef4-0954aa44fa24)

Most NPCs won't line up nicely with the cut in by default, although for some important ones I might take the time to make them a well lined up image (hence the ability to enable it for specific NPCs).

Thank you again for this module!

**Comment by ChasarooniZ** [comment]
Yeah that could work,  may consider trying to see if having an option + having it default to tokens for NPCs (or PCs, or both)

**Comment by ChasarooniZ** [comment]
Added ability to toggle off for NPCs, however going to put the enabling for specific NPCs on the TODO
