### ISSUE TITLE
[Feature] Critical Hit wait for "dice so nice" finished animation

### ISSUE THREAD

**Issue by Yosoy-Ed** [ChasarooniZ/pf2e-rpg-numbers#28]
**Is your feature request related to a problem? Please describe.**

The critical hit image is shown before the dice has finished the dice so nice animation.

**Describe the solution you'd like**
Wait for the roll to be finished.

**Describe alternatives you've considered**
No alternative. 

**Additional context**
As I understand, dice so nice hiddes the chat card and waits for the animation to finish to show it, but the message data is already created in backend so everything related to the message created is executed. There is a Hook in dice so nice to get the message id. I use this to identify if it is being used or not:

Hooks.on("createChatMessage", (chatMessage) => {
    if (!game.modules.get("dice-so-nice")?.active) {
        mycode(chatMessage);
    }
})

Hooks.on('diceSoNiceRollComplete', (data) => {
    let chatMessage = game.messages.get(data);
    mycode(chatMessage);
})

**Comment by ChasarooniZ** [comment]
Will consider, but no promises as this would create extra complications, and my goal is to have this rely on the least number of modules for functionality, 

Will add instead a delay option, as that seems the simpler implementation
