### ISSUE TITLE
[Feature] Add RPG number for healing

### ISSUE THREAD

**Issue by uniwars** [ChasarooniZ/pf2e-rpg-numbers#32]
Hi,

**Is your feature request related to a problem? Please describe.**
With vanilla damage number we see -xxx in red for damage and +xxx in green for healing, but with the module we no longer see healing numbers.

**Describe the solution you'd like**
See damage with a "-" and healing with a "+" and maybe an option to choose color for both.

**Describe alternatives you've considered**
Show vanilla healing number.

**Comment by ChasarooniZ** [comment]
Hmm, I may add healing (just color it nicely or something)

Don't think the adding a + or minus is in scope for my vision of the module ATM tho, as it wouldn't match the visual, but may consider it on the settings revamp (whenever that happens tho as it seems high effort and idk how I'd do that in the first place)

**Comment by uniwars** [comment]
Yeah just having it in green would be awesome.

I don't know if that's normal but I don't see colors neither damages split when applying damage, is that normal ? that doesn't bother me so much but if future healing appears as damage it would be more annoying
![image](https://github.com/ChasarooniZ/pf2e-rpg-numbers/assets/65986545/33af962c-de01-47a9-a0c4-9c231723ca5c)
![image](https://github.com/ChasarooniZ/pf2e-rpg-numbers/assets/65986545/5f3899fe-b619-4afb-bf37-230c30498b69)

**Comment by ChasarooniZ** [comment]
In newest release
