### ISSUE TITLE
[Feature] Per user settings

### ISSUE THREAD

**Issue by uniwars** [ChasarooniZ/pf2e-rpg-numbers#33]
Hi, some of my players doesn't like the critical hit effect, but some like it and I can only deactivate the whole feature for everyone.

**Describe the solution you'd like**
A per user setting to deactivate the module, if possible a setting to activate/deactivate each feature per user.

**Comment by ChasarooniZ** [comment]
Not doable under current framework. Only way to check individual player settings is with running code on their end, May have a scuffed implementation I can try but unsure of its effectiveness
