### ISSUE TITLE
[Bug] No sound effect plays with persona style animation

### ISSUE THREAD

**Issue by TangledLion** [ChasarooniZ/pf2e-rpg-numbers#36]
It works fine with fire emblem but not the persona animation.

**Comment by ChasarooniZ** [comment]
going to need steps to reproduce probably, as I don't seem to have this issue nor do i see where it could be caused in code?

**Comment by TangledLion** [comment]
> going to need steps to reproduce probably, as I don't seem to have this issue nor do i see where it could be caused in code?

Shoot sorry I missed the rel

**Comment by ChasarooniZ** [comment]
weird okeh!
