### ISSUE TITLE
[Bug] Token configuration not working

### ISSUE THREAD

**Issue by Thiagosavin** [ChasarooniZ/pf2e-rpg-numbers#55]
**Describe the bug**
The token configuration for rpg numbers dont work. Don´t show nothing to edit.

**Screenshots**
![image](https://github.com/ChasarooniZ/pf2e-rpg-numbers/assets/24558112/8a182c76-1824-4ddd-8ccd-bad6aa33780c)

Foundry version: 12.327
Module version: 12.0.1

**Comment by ChasarooniZ** [comment]
ah Dang, okay maybe time to startup replacement ui stuff
