### ISSUE TITLE
[Bug] Persona Critical Animation Not Displayed

### ISSUE THREAD

**Issue by asoulliard** [ChasarooniZ/pf2e-rpg-numbers#81]
**DESCRIPTION:** PC token makes attack against enemy token and scores a critical success on the attack roll. Sound is played, but no animation is displayed. [Console log saved here.](https://pastebin.com/EqBmvtK9)

Foundry **v12 Build 331** via Forge
PF2e **6.2.2**
PF2e RPG Number **2.4.8**
Sequencer **3.2.16**
Chrome **Version 128.0.6613.84 (Official Build) (64-bit)**
Windows 10 **Version 22H2 (OS Build 19045.4780)**

# PF2e RPG Numbers Settings

Enable Module: **True**

Enable Damage Numbers: **False**

Enable RPG Checks & Attacks: **False**

Enable Damage Shake: **False**

Enable Token shaking on damage: **False**

Enable Shake on Attack: **False**

Enable Token rotating on attacking: **False**

Enable Critical Animations: **True**
+ Enable Critical Animations - For You: **True**
+ Critical Animation Type: **Persona**
+ Show Critical Animation On: **Both**
+ Show Critical Animation For: **PCs & NPCs**
+ Default Image: **"PCs: Token | NPCs: Token"**
+ Critical Animation Duration: **1.5**
+ Critical Animation Sound: **modules/pf2e-rpg-numbers/resources/sounds/swoosh-universfield.mp3**
+ Critical Animation Volume: **50**
+ Delay: **0**

Enable Finishing Moves: **False**

Debug Mode: **True**

# Token Configuration

Turn on Attack - Rotation Offset: **0**

Fire Emblem Critical Pic: **null**

Persona Critical Pic: **https://assets.forge-vtt.com/62d9874c7c243e74a91fdd3f/Images/Jin%20Cut-In%202.png**

Critical X Offset: **0**

Critical Y Offset: **0**

Crit Scale: **100**

Crit Rotation: **0**

Crit SFX: **null**

**Comment by ChasarooniZ** [comment]
Sequencer bug, wait till they update or revert sequencer version
