### ISSUE TITLE
[Feature] Allow Macros or Random Playlist Sounds

### ISSUE THREAD

**Issue by Armandeus66** [ChasarooniZ/pf2e-rpg-numbers#99]
You can set a sound to play for various things like critical success and so on, but it seems that you must choose one sound.

In addition to that, I would like to suggest allowing a playlist to be set from which a random sound is played.

Allowing a macro (that plays a random sound from a playlist) would be fine, too.

Thanks!

**Comment by ChasarooniZ** [comment]
It currently is supported but its a bit hidden, its only visible through wildcard
https://fantasycomputer.works/FoundryVTT-Sequencer/#/api/sound?id=file

See here for an example. Allowing a playlist is def outside scope of module unfortunately due to it being sequencer though

**Comment by Armandeus66** [comment]
Sorry to ask after you closed the issue, but would a macro be possible?

If not, then the only way would be to have several files that would match with abc*.ogg or something like that, right?

Thanks.

**Comment by ChasarooniZ** [comment]
Macro isn't really in the cards as the UI for it would be significantly different than the sound effect UI. I'd recommend either changing your specific sounds to have their names allow for `abc*`


Some alternatives include:
- Edit the code to paste macro directly (it shouldn't be relatively easy to find and replace)
- Not certain on this but I believe you can do something like "{'file1','file2'}"

Best of luck, but under the current way the UI works, I couldn't support macro or playlist and meet my own desires for the design of the module

**Comment by Armandeus66** [comment]
Thanks for the response.

Dice So Nice allows you to choose a macro in place of a sound file, and I was imagining that your module could possibly do the same. (It only allows a sound on a natural roll of X, 1 or 20 for example, so it doesn't support PF2E's +-10 crits).

I have a lot of files I would like to use, and if I rename them all to file1.mp3 it would be hard for me to tell them apart. I'm not sure of the practicality from the user's standpoint.

However, I am grateful for your work and enjoy using your module. Thanks for engaging with my suggestion.

**Comment by ChasarooniZ** [comment]
["modules/pf2e-rpg-numbers/resources/sounds/checks/success_1.mp3","modules/pf2e-rpg-numbers/resources/sounds/checks/correct-answer-tone.ogg"]

**Comment by Armandeus66** [comment]
Thank you.
